### ISSUE TITLE
WaterFall Support

### ISSUE THREAD

**Issue by DokanBoy** [lokha/spigot-logger-for-bungee#1]
Добавь поддержку WaterFall, пожалуйста.

**Comment by lokha** [comment]
@DokanBoy если это форк обычной банги, то должно работать. А что там? Ошибку выдает?

**Comment by DokanBoy** [comment]
Да, ошибку кидает. Надо чуть позже будет тестануть, чтобы уточнить, что именно кидает

**Comment by adsa562** [comment]
hi, the error when I using waterfall looks like:
```
[22:13:50 WARN]: Exception encountered when loading plugin: SpigotLoggerForBungee
>java.lang.NoClassDefFoundError: jline/console/ConsoleReader
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[?:?]
at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44) ~[waterfall-379.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[waterfall-379.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
at ua.lokha.spigotloggerforbungee.SpigotLoggerForBungeePlugin.lambda$disableDefaultConsole$5(SpigotLoggerForBungeePlugin.java:111) ~[?:?]
at ua.lokha.spigotloggerforbungee.utils.Try.unchecked(Try.java:33) ~[?:?]
at ua.lokha.spigotloggerforbungee.SpigotLoggerForBungeePlugin.disableDefaultConsole(SpigotLoggerForBungeePlugin.java:111) ~[?:?]
at ua.lokha.spigotloggerforbungee.SpigotLoggerForBungeePlugin.onEnable(SpigotLoggerForBungeePlugin.java:74) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[waterfall-379.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[waterfall-379.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall-379.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-379.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
>Caused by: java.lang.ClassNotFoundException: jline.console.ConsoleReader
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[waterfall-379.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[waterfall-379.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
... 20 more 
```

**Comment by lokha** [comment]
в течении пары дней займусь этой ошибкой тогда

**Comment by DokanBoy** [comment]
@lokha @adsa562 
In WaterFall (checked in build #379) already has such a feature.
![image](https://user-images.githubusercontent.com/24508965/95684939-f2fab180-0c1e-11eb-96bb-5782a39e52cc.png)

**Comment by lokha** [comment]
yes indeed
